# Generated by Django 4.2.30 on 2026-04-19 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push mobile')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('appointment_requested', 'Demande de rendez-vous'), ('appointment_assigned', 'Rendez-vous assigné'), ('appointment_confirmed', 'Rendez-vous confirmé'), ('appointment_cancelled', 'Rendez-vous annulé'), ('appointment_completed', 'Rendez-vous effectué'), ('appointment_reminder', 'Rappel de rendez-vous'), ('service_updated', 'Service mis à jour'), ('account_verified', 'Compte vérifié'), ('password_reset', 'Réinitialisation du mot de passe')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', "En file d'attente"), ('sending', "En cours d'envoi"), ('delivered', 'Livré'), ('failed', 'Échec'), ('cancelled', 'Annulé')], db_index=True, default='queued', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx'), models.Index(fields=['event_type', 'created_at'], name='notificatio_event_t_4562fd_idx')],
            },
        ),
    ]
