# Generated by Django 4.2.30 on 2026-05-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('appointment_requested', 'Demande de rendez-vous'), ('appointment_assigned', 'Rendez-vous assigné'), ('appointment_confirmed', 'Rendez-vous confirmé'), ('appointment_cancelled', 'Rendez-vous annulé'), ('appointment_completed', 'Rendez-vous effectué'), ('appointment_reminder', 'Rappel de rendez-vous'), ('service_updated', 'Service mis à jour'), ('account_verified', 'Compte vérifié'), ('password_reset', 'Réinitialisation du mot de passe'), ('registration_submitted', "Inscription en attente d'examen"), ('registration_pending_admin', 'Nouvelle inscription à examiner'), ('email_verification', "Vérification de l'adresse email"), ('password_changed', 'Mot de passe modifié'), ('login_new_device', 'Connexion depuis un nouvel appareil')], db_index=True, max_length=50),
        ),
    ]
