# Generated by Django 4.2.30 on 2026-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
    ]
