# Generated by Django 4.2.30 on 2026-04-19 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', "En attente d'un agent"), ('assigned', 'Agent assigné'), ('confirmed', 'Confirmé'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('expired', 'Expiré (aucun agent disponible)'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Motif du rendez-vous fourni par le client.')),
                ('notes', models.TextField(blank=True, default='', help_text="Notes internes (visible uniquement par l'agent et l'admin).")),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, help_text='Human-readable reference, e.g. BNA-2024-00042. Set by AppointmentAccess.', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.agency')),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_appointments', to=settings.AUTH_USER_MODEL)),
                ('agent_assignment', models.ForeignKey(blank=True, help_text='The specific assignment used when the agent accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.agentassignment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role__in': ['client', 'guest']}, on_delete=django.db.models.deletion.PROTECT, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'appointments_appointment',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', "En attente d'un agent"), ('assigned', 'Agent assigné'), ('confirmed', 'Confirmé'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('expired', 'Expiré (aucun agent disponible)'), ('rejected', 'Refusé')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', "En attente d'un agent"), ('assigned', 'Agent assigné'), ('confirmed', 'Confirmé'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('expired', 'Expiré (aucun agent disponible)'), ('rejected', 'Refusé')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de statut',
                'verbose_name_plural': 'Journal des statuts',
                'db_table': 'appointments_status_log',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='appointment_status_eec9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'status'], name='appointment_client__c919d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['agent', 'status'], name='appointment_agent_i_1f311f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'agency', 'scheduled_at'], name='appointment_service_99b683_idx'),
        ),
    ]
