# Generated by Django 4.2.30 on 2026-04-19 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('suspended', 'Suspendue temporairement')], db_index=True, default='open', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Nombre maximum de rendez-vous simultanés.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'db_table': 'services_agency',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('thursday_close', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('saturday_close', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_services', to='services.agency')),
            ],
            options={
                'verbose_name': 'Service en agence',
                'verbose_name_plural': 'Services en agence',
                'db_table': 'services_agency_service',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('retail', 'Particuliers'), ('corporate', 'Entreprises'), ('investment', 'Investissement'), ('insurance', 'Assurance'), ('digital', 'Digital & Technologie')], max_length=30)),
                ('type', models.CharField(choices=[('account', 'Gestion de compte'), ('credit', 'Crédit et financement'), ('card', 'Carte bancaire'), ('transfer', 'Virement et paiement'), ('advisory', 'Conseil et patrimoine'), ('other', 'Autre')], max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text="Durée standard d'un rendez-vous pour ce service (en minutes).")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_service',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='services.agencyservice')),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.PROTECT, related_name='agent_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Affectation d'agent",
                'verbose_name_plural': "Affectations d'agents",
                'db_table': 'services_agent_assignment',
            },
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='agency',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='agencies', through='services.AgencyService', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_d8f4e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentassignment',
            unique_together={('agent', 'agency_service')},
        ),
        migrations.AlterUniqueTogether(
            name='agencyservice',
            unique_together={('agency', 'service')},
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['city', 'status'], name='services_ag_city_942bf5_idx'),
        ),
    ]
